# This file provides project-level configuration for the canon dev environment utility. https://github.com/viamrobotics/canon
ocean-prefilter:
    default: true
    image_amd64: ghcr.io/viam-labs/ocean-prefilter:amd64
    image_arm64: ghcr.io/viam-labs/ocean-prefilter:arm64
    user: testbot
    group: testbot
    persistent: true

viam-rdk:
    image_amd64: ghcr.io/viamrobotics/rdk-devenv:amd64-cache
    image_arm64: ghcr.io/viamrobotics/rdk-devenv:arm64-cache
    image_arm: ghcr.io/viamrobotics/rdk-devenv:armhf-cache
    minimum_date: 2023-10-26T20:00:00.0Z
    update_interval: 168h0m0s
    user: testbot
    group: testbot
    persistent: true

