name: Build arm64 module

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: Upload module for linux/arm64
    runs-on: [buildjet-2vcpu-ubuntu-2204-arm]
    container:
      image: ghcr.io/viam-labs/ocean-prefilter:arm64
      options: --platform linux/arm64
    timeout-minutes: 30
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build
        run: make module.tar.gz
      - name: Upload
        uses: viamrobotics/upload-module@v1
        with:
          platform: linux/arm64 
          version: ${{ github.ref_name }} 
          key-id: ${{ secrets.viam_key_id }}
          key-value: ${{ secrets.viam_key_value }}
